INSERT INTO tlkpStates (StateCode, StateName, FederalTaxRate, StateTaxRate, HasStateLottery, HasPowerPlay, HasDoublePlay) VALUES ('AL','Alabama',0.24,0.00,FALSE,FALSE,FALSE);
INSERT INTO tlkpStates (StateCode, StateName, FederalTaxRate, StateTaxRate, HasStateLottery, HasPowerPlay, HasDoublePlay) VALUES ('AK','Alaska',0.24,0.00,FALSE,FALSE,FALSE);
INSERT INTO tlkpStates (StateCode, StateName, FederalTaxRate, StateTaxRate, HasStateLottery, HasPowerPlay, HasDoublePlay) VALUES ('AZ','Arizona',0.24,0.05,TRUE,TRUE,FALSE);
INSERT INTO tlkpStates (StateCode, StateName, FederalTaxRate, StateTaxRate, HasStateLottery, HasPowerPlay, HasDoublePlay) VALUES ('AR','Arkansas',0.24,0.055,TRUE,TRUE,FALSE);
INSERT INTO tlkpStates (StateCode, StateName, FederalTaxRate, StateTaxRate, HasStateLottery, HasPowerPlay, HasDoublePlay) VALUES ('CA','California',0.24,0.00,TRUE,TRUE,FALSE);
INSERT INTO tlkpStates (StateCode, StateName, FederalTaxRate, StateTaxRate, HasStateLottery, HasPowerPlay, HasDoublePlay) VALUES ('CO','Colorado',0.24,0.04,TRUE,TRUE,TRUE);
INSERT INTO tlkpStates (StateCode, StateName, FederalTaxRate, StateTaxRate, HasStateLottery, HasPowerPlay, HasDoublePlay) VALUES ('CT','Connecticut',0.24,0.0699,TRUE,TRUE,FALSE);
INSERT INTO tlkpStates (StateCode, StateName, FederalTaxRate, StateTaxRate, HasStateLottery, HasPowerPlay, HasDoublePlay) VALUES ('DE','Delaware',0.24,0.00,TRUE,TRUE,FALSE);
INSERT INTO tlkpStates (StateCode, StateName, FederalTaxRate, StateTaxRate, HasStateLottery, HasPowerPlay, HasDoublePlay) VALUES ('DC','District of Columbia',0.24,0.0875,TRUE,TRUE,FALSE);
INSERT INTO tlkpStates (StateCode, StateName, FederalTaxRate, StateTaxRate, HasStateLottery, HasPowerPlay, HasDoublePlay) VALUES ('FL','Florida',0.24,0.00,TRUE,TRUE,TRUE);
INSERT INTO tlkpStates (StateCode, StateName, FederalTaxRate, StateTaxRate, HasStateLottery, HasPowerPlay, HasDoublePlay) VALUES ('GA','Georgia',0.24,0.055,TRUE,TRUE,FALSE);
INSERT INTO tlkpStates (StateCode, StateName, FederalTaxRate, StateTaxRate, HasStateLottery, HasPowerPlay, HasDoublePlay) VALUES ('HI','Hawaii',0.24,0.00,FALSE,FALSE,FALSE);
INSERT INTO tlkpStates (StateCode, StateName, FederalTaxRate, StateTaxRate, HasStateLottery, HasPowerPlay, HasDoublePlay) VALUES ('ID','Idaho',0.24,0.058,TRUE,TRUE,FALSE);
INSERT INTO tlkpStates (StateCode, StateName, FederalTaxRate, StateTaxRate, HasStateLottery, HasPowerPlay, HasDoublePlay) VALUES ('IL','Illinois',0.24,0.0495,TRUE,TRUE,FALSE);
INSERT INTO tlkpStates (StateCode, StateName, FederalTaxRate, StateTaxRate, HasStateLottery, HasPowerPlay, HasDoublePlay) VALUES ('IN','Indiana',0.24,0.0323,TRUE,TRUE,TRUE);
INSERT INTO tlkpStates (StateCode, StateName, FederalTaxRate, StateTaxRate, HasStateLottery, HasPowerPlay, HasDoublePlay) VALUES ('IA','Iowa',0.24,0.06,TRUE,TRUE,FALSE);
INSERT INTO tlkpStates (StateCode, StateName, FederalTaxRate, StateTaxRate, HasStateLottery, HasPowerPlay, HasDoublePlay) VALUES ('KS','Kansas',0.24,0.05,TRUE,TRUE,FALSE);
INSERT INTO tlkpStates (StateCode, StateName, FederalTaxRate, StateTaxRate, HasStateLottery, HasPowerPlay, HasDoublePlay) VALUES ('KY','Kentucky',0.24,0.05,TRUE,TRUE,FALSE);
INSERT INTO tlkpStates (StateCode, StateName, FederalTaxRate, StateTaxRate, HasStateLottery, HasPowerPlay, HasDoublePlay) VALUES ('LA','Louisiana',0.24,0.05,TRUE,TRUE,FALSE);
INSERT INTO tlkpStates (StateCode, StateName, FederalTaxRate, StateTaxRate, HasStateLottery, HasPowerPlay, HasDoublePlay) VALUES ('ME','Maine',0.24,0.05,TRUE,TRUE,FALSE);
INSERT INTO tlkpStates (StateCode, StateName, FederalTaxRate, StateTaxRate, HasStateLottery, HasPowerPlay, HasDoublePlay) VALUES ('MD','Maryland',0.24,0.0875,TRUE,TRUE,FALSE);
INSERT INTO tlkpStates (StateCode, StateName, FederalTaxRate, StateTaxRate, HasStateLottery, HasPowerPlay, HasDoublePlay) VALUES ('MA','Massachusetts',0.24,0.05,TRUE,TRUE,FALSE);
INSERT INTO tlkpStates (StateCode, StateName, FederalTaxRate, StateTaxRate, HasStateLottery, HasPowerPlay, HasDoublePlay) VALUES ('MI','Michigan',0.24,0.0425,TRUE,TRUE,FALSE);
INSERT INTO tlkpStates (StateCode, StateName, FederalTaxRate, StateTaxRate, HasStateLottery, HasPowerPlay, HasDoublePlay) VALUES ('MN','Minnesota',0.24,0.0785,TRUE,TRUE,FALSE);
INSERT INTO tlkpStates (StateCode, StateName, FederalTaxRate, StateTaxRate, HasStateLottery, HasPowerPlay, HasDoublePlay) VALUES ('MS','Mississippi',0.24,0.05,FALSE,FALSE,FALSE);
INSERT INTO tlkpStates (StateCode, StateName, FederalTaxRate, StateTaxRate, HasStateLottery, HasPowerPlay, HasDoublePlay) VALUES ('MO','Missouri',0.24,0.0495,TRUE,TRUE,TRUE);
INSERT INTO tlkpStates (StateCode, StateName, FederalTaxRate, StateTaxRate, HasStateLottery, HasPowerPlay, HasDoublePlay) VALUES ('MT','Montana',0.24,0.069,TRUE,TRUE,FALSE);
INSERT INTO tlkpStates (StateCode, StateName, FederalTaxRate, StateTaxRate, HasStateLottery, HasPowerPlay, HasDoublePlay) VALUES ('NE','Nebraska',0.24,0.0684,TRUE,TRUE,FALSE);
INSERT INTO tlkpStates (StateCode, StateName, FederalTaxRate, StateTaxRate, HasStateLottery, HasPowerPlay, HasDoublePlay) VALUES ('NV','Nevada',0.24,0.00,FALSE,FALSE,FALSE);
INSERT INTO tlkpStates (StateCode, StateName, FederalTaxRate, StateTaxRate, HasStateLottery, HasPowerPlay, HasDoublePlay) VALUES ('NH','New Hampshire',0.24,0.00,TRUE,TRUE,FALSE);
INSERT INTO tlkpStates (StateCode, StateName, FederalTaxRate, StateTaxRate, HasStateLottery, HasPowerPlay, HasDoublePlay) VALUES ('NJ','New Jersey',0.24,0.08,TRUE,TRUE,FALSE);
INSERT INTO tlkpStates (StateCode, StateName, FederalTaxRate, StateTaxRate, HasStateLottery, HasPowerPlay, HasDoublePlay) VALUES ('NM','New Mexico',0.24,0.059,TRUE,TRUE,FALSE);
INSERT INTO tlkpStates (StateCode, StateName, FederalTaxRate, StateTaxRate, HasStateLottery, HasPowerPlay, HasDoublePlay) VALUES ('NY','New York',0.24,0.0882,TRUE,TRUE,FALSE);
INSERT INTO tlkpStates (StateCode, StateName, FederalTaxRate, StateTaxRate, HasStateLottery, HasPowerPlay, HasDoublePlay) VALUES ('NC','North Carolina',0.24,0.0525,TRUE,TRUE,FALSE);
INSERT INTO tlkpStates (StateCode, StateName, FederalTaxRate, StateTaxRate, HasStateLottery, HasPowerPlay, HasDoublePlay) VALUES ('ND','North Dakota',0.24,0.029,TRUE,TRUE,FALSE);
INSERT INTO tlkpStates (StateCode, StateName, FederalTaxRate, StateTaxRate, HasStateLottery, HasPowerPlay, HasDoublePlay) VALUES ('OH','Ohio',0.24,0.04,TRUE,TRUE,FALSE);
INSERT INTO tlkpStates (StateCode, StateName, FederalTaxRate, StateTaxRate, HasStateLottery, HasPowerPlay, HasDoublePlay) VALUES ('OK','Oklahoma',0.24,0.0475,TRUE,TRUE,FALSE);
INSERT INTO tlkpStates (StateCode, StateName, FederalTaxRate, StateTaxRate, HasStateLottery, HasPowerPlay, HasDoublePlay) VALUES ('OR','Oregon',0.24,0.09,TRUE,TRUE,FALSE);
INSERT INTO tlkpStates (StateCode, StateName, FederalTaxRate, StateTaxRate, HasStateLottery, HasPowerPlay, HasDoublePlay) VALUES ('PA','Pennsylvania',0.24,0.0307,TRUE,TRUE,TRUE);
INSERT INTO tlkpStates (StateCode, StateName, FederalTaxRate, StateTaxRate, HasStateLottery, HasPowerPlay, HasDoublePlay) VALUES ('RI','Rhode Island',0.24,0.0599,TRUE,TRUE,FALSE);
INSERT INTO tlkpStates (StateCode, StateName, FederalTaxRate, StateTaxRate, HasStateLottery, HasPowerPlay, HasDoublePlay) VALUES ('SC','South Carolina',0.24,0.07,TRUE,TRUE,FALSE);
INSERT INTO tlkpStates (StateCode, StateName, FederalTaxRate, StateTaxRate, HasStateLottery, HasPowerPlay, HasDoublePlay) VALUES ('SD','South Dakota',0.24,0.00,TRUE,TRUE,FALSE);
INSERT INTO tlkpStates (StateCode, StateName, FederalTaxRate, StateTaxRate, HasStateLottery, HasPowerPlay, HasDoublePlay) VALUES ('TN','Tennessee',0.24,0.00,TRUE,TRUE,TRUE);
INSERT INTO tlkpStates (StateCode, StateName, FederalTaxRate, StateTaxRate, HasStateLottery, HasPowerPlay, HasDoublePlay) VALUES ('TX','Texas',0.24,0.00,TRUE,TRUE,TRUE);
INSERT INTO tlkpStates (StateCode, StateName, FederalTaxRate, StateTaxRate, HasStateLottery, HasPowerPlay, HasDoublePlay) VALUES ('UT','Utah',0.24,0.00,FALSE,FALSE,FALSE);
INSERT INTO tlkpStates (StateCode, StateName, FederalTaxRate, StateTaxRate, HasStateLottery, HasPowerPlay, HasDoublePlay) VALUES ('VT','Vermont',0.24,0.06,TRUE,TRUE,FALSE);
INSERT INTO tlkpStates (StateCode, StateName, FederalTaxRate, StateTaxRate, HasStateLottery, HasPowerPlay, HasDoublePlay) VALUES ('VA','Virginia',0.24,0.04,TRUE,TRUE,FALSE);
INSERT INTO tlkpStates (StateCode, StateName, FederalTaxRate, StateTaxRate, HasStateLottery, HasPowerPlay, HasDoublePlay) VALUES ('WA','Washington',0.24,0.00,TRUE,TRUE,FALSE);
INSERT INTO tlkpStates (StateCode, StateName, FederalTaxRate, StateTaxRate, HasStateLottery, HasPowerPlay, HasDoublePlay) VALUES ('WV','West Virginia',0.24,0.065,TRUE,TRUE,FALSE);
INSERT INTO tlkpStates (StateCode, StateName, FederalTaxRate, StateTaxRate, HasStateLottery, HasPowerPlay, HasDoublePlay) VALUES ('WI','Wisconsin',0.24,0.0765,TRUE,TRUE,FALSE);
INSERT INTO tlkpStates (StateCode, StateName, FederalTaxRate, StateTaxRate, HasStateLottery, HasPowerPlay, HasDoublePlay) VALUES ('WY','Wyoming',0.24,0.00,TRUE,TRUE,FALSE);